### ISSUE TITLE
How to use this as cli command?

### ISSUE THREAD

**Issue by salsa2k** [MestreLion/legendastv#24]
Hi,

How I use this?
How can I search for something using command line?

Thanks

**Comment by MestreLion** [comment]
Yes, of course...  the main script is `legendastv.py`, it is an executable script, and it accepts video files or directories as arguments, so you can use it as `./legendas.py [PATH...]`, for example `./legendas.py ~/Videos/MyTVShow/*.mkv`, and it will recursively search, choose, download, extract and rename subtitles for all requested videos using Legendas.TV website subtitle database.

On first-time usage a blank config file will be created at `~/.config/legendastv/legendastv.cfg`. Edit it and fill your LegendasTV website username and passowrd, and run it again.
